-- Project statuses cut down to four: IN_PREGATIRE (CIORNA renamed), IN_PRODUCTIE,
-- FINALIZAT and SUSPENDAT. Production held no project in the dropped statuses,
-- but every old value is still mapped, so the deploy cannot fail on a stray row:
--   CIORNA, IN_OFERTARE, CASTIGAT, IN_PROIECTARE -> IN_PREGATIRE
--   PREGATIT_LIVRARE                             -> IN_PRODUCTIE
--   LIVRAT                                       -> FINALIZAT (keeps its completedAt)
--   ANULAT                                       -> SUSPENDAT
--
-- Postgres cannot drop enum values, so a new type replaces the old one. The
-- generated statusRank column and its index depend on `status` and are rebuilt.

DROP INDEX "projects_statusRank_startDate_idx";
ALTER TABLE "projects" DROP COLUMN "statusRank";
ALTER TABLE "projects" ALTER COLUMN "status" DROP DEFAULT;

CREATE TYPE "ProjectStatus_new" AS ENUM ('IN_PREGATIRE', 'IN_PRODUCTIE', 'FINALIZAT', 'SUSPENDAT');

ALTER TABLE "projects"
  ALTER COLUMN "status" TYPE "ProjectStatus_new"
  USING (
    CASE "status"::text
      WHEN 'IN_PRODUCTIE' THEN 'IN_PRODUCTIE'
      WHEN 'PREGATIT_LIVRARE' THEN 'IN_PRODUCTIE'
      WHEN 'FINALIZAT' THEN 'FINALIZAT'
      WHEN 'LIVRAT' THEN 'FINALIZAT'
      WHEN 'SUSPENDAT' THEN 'SUSPENDAT'
      WHEN 'ANULAT' THEN 'SUSPENDAT'
      ELSE 'IN_PREGATIRE'
    END
  )::"ProjectStatus_new";

DROP TYPE "ProjectStatus";
ALTER TYPE "ProjectStatus_new" RENAME TO "ProjectStatus";

ALTER TABLE "projects" ALTER COLUMN "status" SET DEFAULT 'IN_PREGATIRE';

-- A project mapped out of the finished set must not keep a completion date.
UPDATE "projects" SET "completedAt" = NULL WHERE "status" <> 'FINALIZAT' AND "completedAt" IS NOT NULL;

-- Sort rank for the default project ordering: IN_PRODUCTIE first, FINALIZAT last.
-- Generated by Postgres so it can never drift from `status`; the application
-- must never write this column.
ALTER TABLE "projects"
  ADD COLUMN "statusRank" INTEGER NOT NULL GENERATED ALWAYS AS (
    CASE "status"
      WHEN 'IN_PRODUCTIE' THEN 0
      WHEN 'IN_PREGATIRE' THEN 1
      WHEN 'SUSPENDAT' THEN 2
      WHEN 'FINALIZAT' THEN 3
      ELSE 99
    END
  ) STORED;

CREATE INDEX "projects_statusRank_startDate_idx" ON "projects" ("statusRank", "startDate");
