-- Sort rank for the default project ordering: IN_PRODUCTIE first, then the rest of
-- the workflow in order, FINALIZAT last. Generated by Postgres so it can never drift
-- from `status`; the application must never write this column.
ALTER TABLE "projects"
  ADD COLUMN "statusRank" INTEGER NOT NULL GENERATED ALWAYS AS (
    CASE "status"
      WHEN 'IN_PRODUCTIE' THEN 0
      WHEN 'CIORNA' THEN 1
      WHEN 'IN_OFERTARE' THEN 2
      WHEN 'CASTIGAT' THEN 3
      WHEN 'IN_PROIECTARE' THEN 4
      WHEN 'PREGATIT_LIVRARE' THEN 5
      WHEN 'LIVRAT' THEN 6
      WHEN 'SUSPENDAT' THEN 7
      WHEN 'ANULAT' THEN 8
      WHEN 'FINALIZAT' THEN 9
      ELSE 99
    END
  ) STORED;

-- Matches the default ordering: rank, then start date, then id.
CREATE INDEX "projects_statusRank_startDate_idx" ON "projects" ("statusRank", "startDate");
